version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: backend-app
    tty: true
    ports:
      - '3306:3306'
      - '5555:5555'
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: backend-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker